### Login

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "jjj",
  "password": "heslo",
  "role": "admin"
}

### Register

POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "jjj",
  "password": "heslo",
  "role": "admin"
}

### Get info

GET http://localhost:3000/user/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InhwaXNhcm92IiwiaWF0IjoxNjQ2NjQ4NTAwfQ.glFwNCz-COBG-B8AiiNAQmjZfwx0haPoz7lxABVQJik

### Update

PUT http://localhost:3000/user/1
Content-Type: application/json

{
  "username": "himmmel",
  "password": "password",
  "role": "pro"
}

### Delete

DELETE http://localhost:3000/user/1
Accept: application/json